server:
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: my-own-book

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:book
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  data:
    web:
      pageable:
        serialization-mode: via_dto

springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    default-model-expand-depth: 2
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  model-and-view-allowed: true
  paths-to-match:
    - /books/**


app:
  security:
    jwt:
      keystore-location:  jwt-keystore.jks
      keystore-password: password
      key-alias: jwt-sign-key
      private-key-passphrase: password
